// Auto-generated by scripts/sync-brand-dna-assets.mjs
// Do not edit manually. Re-run the sync script after source updates.

export type BrandDnaProfile = {
  slug: string
  name?: string
  websiteUrl?: string
  overview?: string
  tagline?: string
  brandValues: string[]
  visualAesthetics: string[]
  toneOfVoice: string[]
  fonts: string[]
  colors: string[]
  campaignCreativeTitles: string[]
  imageFiles: string[]
  featuredImageFiles: string[]
}

export const BRAND_DNA_PROFILES: Record<string, BrandDnaProfile> = {
  "317-bbq": {
    slug: "317-bbq",
    name: "317 BBQ",
    websiteUrl: "https://317bbq.com/",
    overview: "317 BBQ is an Indianapolis-based restaurant in Broad Ripple Village specializing in authentic smoked meats, scratch-made sides, and local craft beer. Through a \"Community Collaborative\" approach, they combine a test-kitchen mentality with traditional BBQ techniques to serve locals in a welcoming, family-and-dog-friendly environment.",
    brandValues: ["Community Collaborative", "Proudly Indiana", "Test Kitchen Mentality", "Passion for Excellence", "Team Collaboration"],
    visualAesthetics: ["rugged authenticity", "smoky industrialism", "bold minimalism", "warm hospitality", "handcrafted tradition"],
    toneOfVoice: ["Welcoming", "Friendly", "Passionate", "Authentic"],
    fonts: ["averia libre", "raleway"],
    colors: [],
    campaignCreativeTitles: [],
    imageFiles: ["screencapture-labs-google-u-0-pomelli-review-2026-04-01-23_24_23.png"],
    featuredImageFiles: ["screencapture-labs-google-u-0-pomelli-review-2026-04-01-23_24_23.png"],
  },
  "graston-technique": {
    slug: "graston-technique",
    name: "Graston Technique",
    websiteUrl: "https://grastontechnique.com/",
    overview: "Graston Technique is a specialized provider of evidence-based Instrument-Assisted Soft Tissue Mobilization (IASTM) therapy — delivering medical-grade stainless-steel instruments, clinician training, and continuing education programs to physical therapists, chiropractors, and allied health professionals.",
    brandValues: ["Evidence-based Practice", "Clinical Excellence", "Innovation", "Professional Integrity"],
    visualAesthetics: ["Clinical Authority", "Modern Healthcare", "Educational Clarity", "Trustworthy Science", "Proactive Recovery"],
    toneOfVoice: ["Professional", "Authoritative", "Educational", "Clinical"],
    fonts: ["Montserrat"],
    colors: [],
    campaignCreativeTitles: ["Command the Spring Sports Surge", "The April Rush is Coming", "Precision Tools for Elite Recovery", "Become the Gold Standard", "May Is For Peak Performance", "Target The Restriction", "Precision-Engineered Tools", "Accelerate Return-To-Play", "Detect what hands cannot feel", "Reduce physical hand strain", "Unmatched tactile feedback", "Elevate your clinical outcomes"],
    imageFiles: ["intricate-tissue-mobilization.png", "mobility-is-mental-health.png", "precision-for-every-ot.png", "resource_81iskZQfO8EburhVsqpOJo.png", "resource_8aHBXffTEo53cEf48Lo4jp.png", "resource_8eSKS2D68gF1xOP1xohO8s.png", "resource_8iCm6i6mfAu4E4pxNYhOTh.png", "resource_8tbiAhRccSnd1T4JdLjOvb.png", "resource_98Im5g4eS1H2ja3TB4bOmL.png", "resource_9GhfCwFNKcE9uUG6GlNk-X.png", "resource_9itzwnIrojUa29t2KbF4l9.png", "resource_9Qk8VUxbD5M7mjdP_1P40h.png", "resource_9R0WKP7sRm-6QP9Xg2iO1m.png", "resource_a-8bbgVoQ0t0Bka_kIB_ra.png", "resource_a9fWT7ByAgOekcAQdnM4fR.png", "resource_aezgVyyqONr5NqtUz0A_Xx.png", "resource_afJaycdKPMkdVlXz4DCOUb.png", "resource_ajRbZg9sXiJecWJJXCYOBm.png", "resource_av0XfUO_gwq00jX_TxZkn4.png", "resource_bd8TdzKhqI0bn_IgmYbkGu.png", "resource_bf8KBYjG1gg1BwV2Dh_OfV.png", "resource_bzX0Tkx_yN0eqPjMcmTknM.png"],
    featuredImageFiles: ["resource_9itzwnIrojUa29t2KbF4l9.png", "resource_8eSKS2D68gF1xOP1xohO8s.png", "resource_98Im5g4eS1H2ja3TB4bOmL.png", "resource_9R0WKP7sRm-6QP9Xg2iO1m.png"],
  },
  "hoosier-boy-barbershop": {
    slug: "hoosier-boy-barbershop",
    name: "Hoosier Boy Barbershop",
    websiteUrl: "https://hoosierboybarbershop.com/",
    overview: "Hoosier Boy Barbershop is a Noblesville-based grooming destination founded in 2022 by Jimmy Bissonette and Nathan Gouty. The shop offers professional haircuts and beard grooming services while emphasizing community, artistic creativity, and a relaxed environment for men to unwind.",
    brandValues: ["Community", "Quality", "Innovation", "Sustainability", "Self-expression"],
    visualAesthetics: ["Tattoo-Culture Inspired", "Moody Industrialism", "Playful Eccentricity", "Modern Masculinity", "Craft-Focused"],
    toneOfVoice: ["Whimsical", "Playful", "Relatable", "Creative", "Masculine"],
    fonts: ["playfair display", "montserrat"],
    colors: [],
    campaignCreativeTitles: ["Lighten Your Head and Mind", "The 30-Minute Reset", "Find Connection in the Chair", "Leave Feeling Like You", "Shed the Winter Weight.", "Trade Scruff for Precision.", "A Fresh Perspective.", "Your Spring Starts Here.", "Style With A Soul", "Built For The Bold", "Masterful Fades", "Always Back Home"],
    imageFiles: ["resource_89py8ySromj5MTL_KuDOrA.png", "resource_8obX0HDS6Pk5STzh4yS4u1.png", "resource_8ql27m75qQ0aATLRJW8O0h.png", "resource_8XWNQbdaJ1R52z1g5qFORc.png", "resource_9FjPd50ICCabdQ_bqS2_u0.png", "resource_9fmpcJno4Uy2A32tnt2_M6.png", "resource_9iZ5DRu3UPb6yrik9u64b5.png", "resource_9OWdV4GTvnbfmBkvdKAOhB.png", "resource_aH_Jdyc-4sB6G33odEJ_zx.png", "resource_aNG_LpcnbjQ0DTKw0PmODK.png", "resource_bNRVJnWNWut1D0H4_A_kv9.png", "resource_bsyYzEbN04D02Bl_ZZh_0z.png", "screencapture-labs-google-u-0-pomelli-review-2026-04-01-23_14_22.png"],
    featuredImageFiles: ["screencapture-labs-google-u-0-pomelli-review-2026-04-01-23_14_22.png", "resource_89py8ySromj5MTL_KuDOrA.png", "resource_9fmpcJno4Uy2A32tnt2_M6.png", "resource_bNRVJnWNWut1D0H4_A_kv9.png"],
  },
  "riley-bennett-egloff": {
    slug: "riley-bennett-egloff",
    name: "Riley Bennett Egloff",
    websiteUrl: "https://rbelaw.com/",
    overview: "Riley Bennett Egloff is an Indianapolis-based law firm established in 1979 that serves businesses, government entities, and individuals. They offer the depth of experience found in large firms combined with the personalized attention of a boutique practice, focusing on cost-effective, results-oriented legal solutions across various industries.",
    brandValues: ["Camaraderie", "Community", "Continuity", "Ethics", "Cost-effectiveness"],
    visualAesthetics: ["Modern Heritage", "Tactile Heritage", "Professional", "Authoritative", "Polished Professionalism"],
    toneOfVoice: ["Professional", "Authoritative", "Trustworthy", "Collaborative"],
    fonts: ["open sans"],
    colors: [],
    campaignCreativeTitles: ["Indiana's Elite Legal Team", "Litigation and Employment Law", "Specialized Construction Law", "Strategic Corporate Guidance", "16 Super Lawyers. One Firm.", "Big Firm Skill, Boutique Care", "Proven Indiana Leadership", "Secure Your Business Future", "Scale Your Business With Confidence", "Growth Requires a Solid Foundation", "Local Expertise for Global Goals", "Secure Your Growth Today"],
    imageFiles: ["resource_834JnydkhtiaahwRtY-4wG.png", "resource_8BxdoUrqtlG9pzMj61skRj.png", "resource_8cTNQvU2ONr7wcVagsw4Yc.png", "resource_8qW75ai6jpbeK38VW_0kTI.png", "resource_8wV1luF2UrY9mx5dQJl_hd.png", "resource_8YDHpPDKa8a9MmBcmrN_sl.png", "resource_96zXueuFfOjfQgr6fLP4Hr.png", "resource_9KP-ATITaHt3Rh0rPhq_LH.png", "resource_aBHDj7fTYe37s49AvQWOA2.png", "resource_abkRFLAsJa2cWtBFF8Sk9O.png", "resource_b-SO5Y4obxJ3ZRJ_Ff6__k.png", "resource_bBAdCJBqFZ-bnpHTww2_Mw.png"],
    featuredImageFiles: ["resource_aBHDj7fTYe37s49AvQWOA2.png", "resource_8qW75ai6jpbeK38VW_0kTI.png", "resource_bBAdCJBqFZ-bnpHTww2_Mw.png", "resource_abkRFLAsJa2cWtBFF8Sk9O.png"],
  },
  "russell-painting": {
    slug: "russell-painting",
    name: "Russell Painting Company, Inc.",
    websiteUrl: "https://russellpaintingcompany.com/",
    overview: "Russell Painting Company is a family-owned residential and commercial painting contractor serving the Indianapolis metropolitan area. Since 1993, they have provided high-quality interior and exterior painting, power washing, and deck restoration services to homeowners and businesses throughout Central Indiana.",
    tagline: "Fast and reliable painting services for your home and business.",
    brandValues: [],
    visualAesthetics: [],
    toneOfVoice: [],
    fonts: ["Work Sans", "Montserrat"],
    colors: ["#ffffff", "#269ebf", "#1e383f", "#215d82", "#333333"],
    campaignCreativeTitles: [],
    imageFiles: ["resource_8fyetQv8eVs7jLD3hLo_Le.png", "resource_8uSuhFMM3dqdUikF1Pu_N7.png", "resource_8W7DpKg8J9g3T60Tq29_Qj.png", "resource_aBDcY-2cwlbdAGwl4ChOAY.png", "resource_aQlU7oP-TSU7kBCkZa9O_S.png", "resource_auz9d7JcRT9cTvusPczkhF.png", "resource_b8AcXIliLDR2_mCCDUA_rF.png", "resource_baEX_KanVtSdnBIik43_-f.png", "screencapture-labs-google-u-0-pomelli-review-2026-04-01-23_19_53.png"],
    featuredImageFiles: ["screencapture-labs-google-u-0-pomelli-review-2026-04-01-23_19_53.png", "resource_8fyetQv8eVs7jLD3hLo_Le.png", "resource_8uSuhFMM3dqdUikF1Pu_N7.png", "resource_8W7DpKg8J9g3T60Tq29_Qj.png"],
  },
  "urgentcare-indy": {
    slug: "urgentcare-indy",
    name: "UrgentCare Indy",
    websiteUrl: "https://urgentcareindy.com/",
    overview: "UrgentCare Indy is a walk-in medical clinic in Indianapolis providing affordable treatment for minor illnesses and injuries. As a division of Pike Medical Consultants, they offer on-site labs, vaccines, physicals, and occupational health services, serving as a convenient, cost-effective alternative to emergency room visits for patients aged two and up.",
    brandValues: ["Compassion", "Devotion", "Respect", "Continuity of Care"],
    visualAesthetics: ["approachable", "clinical", "community-oriented", "trustworthy", "compassionate"],
    toneOfVoice: ["Professional", "Reassuring", "Compassionate", "Accessible"],
    fonts: ["asap condensed", "asap"],
    colors: [],
    campaignCreativeTitles: ["Indy Spring: Bloom or Gloom?", "The ER Isn't for Allergies", "Fast, Professional Relief", "Breathe Easy, Indianapolis", "Ready for summer sports?", "All-in-one seasonal care.", "Professional check-ups.", "Cleared for the season.", "Save Time, Skip the ER", "Minutes, Not Hours", "Transparent Pricing", "On-Site Lab Results"],
    imageFiles: ["resource_848PQ9XXM56c_AZnwqG4jq.png", "resource_8uM4IQ5uUni2yQhyHNKOE4.png", "resource_9F9orTGrdWndErv0VUQOr-.png", "resource_9ovca9b4o9uazASoYud_B_.png", "resource_aCWIMLq1L5A1--UYYADkX-.png", "resource_aDvKo4c9l5ndio_YoJtkA8.png", "resource_anFJVaSt3O8d0dWJZSJkev.png", "resource_aTIoXB3iB2WdOy3IbjK_mA.png", "resource_b3zGP4Ats_M3bhkoacn4fO.png", "resource_ba-DSsxnN4ccHw4Pz3X45m.png", "resource_blN2W6lSis2eDurYR3VOCr.png", "resource_bnoa5zZUyY1chwRD149kK2.png", "screencapture-labs-google-u-0-pomelli-review-2026-04-01-23_09_38.png"],
    featuredImageFiles: ["screencapture-labs-google-u-0-pomelli-review-2026-04-01-23_09_38.png", "resource_9F9orTGrdWndErv0VUQOr-.png", "resource_blN2W6lSis2eDurYR3VOCr.png", "resource_b3zGP4Ats_M3bhkoacn4fO.png"],
  },
}

